// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbgpvcntoypanolwrxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiZ3B2Y250b3lwYW5vbHdyeGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDE4NzAsImV4cCI6MjA2NTQ3Nzg3MH0.bLJEmIdGW44XKY3kl5l0kl3FMJ7rJshFBQn-7BWYhbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);